### PR TITLE
[WIP] make sure user is a real guest

### LINKED ISSUE #1419: [Suspend] Suspended users can edit/delete own posts
There's not much needed to recreate this, suspend a test user with a post or two and then attempt to edit or delete the past posts as that user.

This appears to be unintentional, but presents some real problems for security and moderation. It's possible for a user to erase evidence of why they were suspended, to openly dispute their suspension, or use it to retaliate by editing/removing critical posts.

### PR DESCRIPTION
**Pull request by sijad**
should fixes flarum/core#1419

### CODE REVIEW

**Comment by sijad** [comment]
marked it as WIP as I'm still investigate potential side effects.

**Comment by tobyzerner** [comment]
I think this is the right solution. We're basically saying that when it comes to checking permissions, a suspended user *is* a guest – which is correct. It's a comprehensive approach, without requiring specific changes in core or references to other extensions.

However, as you've mentioned on Discord, event priorities have been removed in Laravel 5.4, which is problematic. We need this one to run first.

Honestly event priorities wouldn't have been a great solution anyway, because they imply that you know the priorities of other listeners that have been registered, and you know where you want to be placed in the order... which is not true, extensions don't know about each others' internals.

I think a better solution is to build in only two distinct priorities for certain events – in this case, we'd add `BeforeGetPermission` and `BeforeScopeModelVisibility` events. That way, you can either say "I want to register a normal listener", or "I want to do something before all the normal listeners run". What do you think @franzliedke?

(The whole Gate system is due for a rewrite/cleanup, and we will probably refactor out the use of the event dispatcher – but I'm happy for the above solution to be implemented as a stop-gap.)

**Comment by sijad** [comment]
I agree it would be useful if we had a `Before/After + $EVENT_NAME`, or `Prepare + $EVENT_NAME` for certain events.

**Comment by tobyzerner** [comment]
Closing as per https://github.com/flarum/core/issues/1419#issuecomment-398609638

**Pull request closed without merging**
